stages:
  - DeployDev

cache:
  key: $CI_COMMIT_REF_SLUG

  paths:
    - node_modules/

    - .next/cache/

DeployDev:
  stage: DeployDev

  image: node:18.12.1

  only: ["main"]

  script:
    - apt-get update && apt-get install rsync -y && apt-get install openssh-server -y

    - mkdir -p ~/.ssh

    - ssh-keyscan -H "$SERVER_IP" >> ~/.ssh/known_hosts

    - echo "$SSH_KEY_DEV" > ~/.ssh/id_rsa

    - chmod 700 ~/.ssh/id_rsa

    - echo "$DEV_ENV" > .env

    - yarn install

    - CI= && yarn run build

    - rsync --progress -avzh -e "ssh " --rsync-path="sudo rsync" --exclude=".git" . "$SERVER_NAME"@"$SERVER_IP":~/blog

    - ssh "$SERVER_NAME"@"$SERVER_IP" "cd ~/blog && pm2 reload blog --update-env && pm2 save"
